FrontProjectInAsp.Net/Models/Poster.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace FrontProjectInAsp.Net.Models
{
    public class Poster
    {
        public int Id { get; set; }
        public string Discount { get; set; }
        public string Cookie { get; set; }
        public string WeekCount { get; set; }
        public string Image { get; set; }

        [NotMapped]
        [Required]
        public IFormFile Photo { get; set; }



    }
}

FrontProjectInAsp.Net/Areas/AdminArea/Controllers/PosterController.cs
using FrontProjectInAsp.Net.Data;
using FrontProjectInAsp.Net.Models;
using FrontProjectInAsp.Net.Utilities.File;
using FrontProjectInAsp.Net.Utilities.Helpers;
using FrontProjectInAsp.Net.ViewModels.Admin.PosterViewModels;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace FrontProjectInAsp.Net.Areas.AdminArea.Controllers
{
    public class PosterController : Controller
    {
        private readonly AppDbContext _context;
        private readonly IWebHostEnvironment _env;
        public PosterController(AppDbContext context, IWebHostEnvironment env)
        {
            _context = context;
            _env = env;
        }
        public async Task<IActionResult> Index()
        {
            List<Poster> posters = await _context.Posters.ToListAsync();
            return View(posters);

        }

        public IActionResult Detail(int Id)
        {
            var poster = _context.Posters.FirstOrDefault(m => m.Id == Id);
            return View(poster);
        }
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(PosterVM posterVM)
        {

            if (ModelState["Images"].ValidationState == ModelValidationState.Invalid) return View();

            if (ModelState["Discount"].ValidationState == ModelValidationState.Invalid) return View();

            if (ModelState["Cookie"].ValidationState == ModelValidationState.Invalid) return View();

            if (ModelState["WeekCount"].ValidationState == ModelValidationState.Invalid) return View();

            foreach (var photo in posterVM.Images)
            {
                if (!photo.CheckFileType("image/"))
                {
                    ModelState.AddModelError("Photo", "Image type is wrong");
                    return View();
                }

                if (!photo.CheckFileSize(800))
                {
                    ModelState.AddModelError("Photo", "Image size is wrong");
                    return View();
                }

            }

            foreach (var photo in posterVM.Images)
            {
                string fileName = Guid.NewGuid().ToString() + "_" + photo.FileName;


                string path = Helper.GetFilePath(_env.WebRootPath, "assets/img", fileName);

                using (FileStream stream = new FileStream(path, FileMode.Create))
                {
                    await photo.CopyToAsync(stream);
                }






                Poster poster = new Poster
                {
                    Image = fileName,
                    Discount = posterVM.Discount,
                    Cookie = posterVM.Cookie,
                    WeekCount = posterVM.WeekCount

                };

                await _context.Posters.AddAsync(poster);

            }








            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        public async Task<IActionResult> Edit(int Id)
        {
            Poster poster = await GetPosterById(Id);
            if (poster == null) return NotFound();
            return View(poster);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int Id, Poster poster)
        {
            var dbPoster = await GetPosterById(Id);
            if (dbPoster == null) return NotFound();

            if (ModelState["Photo"].ValidationState == ModelValidationState.Invalid) return View();

            if (!poster.Photo.CheckFileType("image/"))
            {
                ModelState.AddModelError("Photo", "Image type is wrong");
                return View(dbPoster);
            }

            if (!poster.Photo.CheckFileSize(800))
            {
                ModelState.AddModelError("Photo", "Image size is wrong");
                return View(dbPoster);
            }

            string path = Helper.GetFilePath(_env.WebRootPath, "assets/img", dbPoster.Image);

            Helper.DeleteFile(path);


            string fileName = Guid.NewGuid().ToString() + "_" + poster.Photo.FileName;

            string newPath = Helper.GetFilePath(_env.WebRootPath, "assets/img", fileName);

            using (FileStream stream = new FileStream(newPath, FileMode.Create))
            {
                await poster.Photo.CopyToAsync(stream);
            }

            dbPoster.Image = fileName;
            dbPoster.Discount = poster.Discount;
            dbPoster.Cookie = poster.Cookie;
            dbPoster.WeekCount = poster.WeekCount;

            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int Id)
        {
            Poster poster = await _context.Posters.Where(m => m.Id == Id).FirstOrDefaultAsync();

            if (poster == null) return NotFound();

            string path = Helper.GetFilePath(_env.WebRootPath, "assets/img", poster.Image);
            Helper.DeleteFile(path);

            _context.Posters.Remove(poster);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }




        private async Task<Poster> GetPosterById(int Id)
        {
            return await _context.Posters.FindAsync(Id);
        }



    }
}

FrontProjectInAsp.Net/Areas/AdminArea/Views/Poster/Create.cshtml
@model Poster

@{
    ViewData["Title"] = "Create";
    Layout = "~/Areas/AdminArea/Views/Shared/_AdminLayout.cshtml";
}

<div class="container my-5">
    <form class="forms-sample mt-5" method="post" asp-action="Create" enctype="multipart/form-data">
        @*<div class="form-group">
            <label asp-for="Images"></label>
            <input class="form-control" style="width:300px" asp-for="Images">
            <span class="text-danger" asp-validation-for="Images"></span>
        </div>*@
        <div class="form-group">
            <label asp-for="Discount">Discount:</label>
            <input class="form-control" style="width:300px" asp-for="Discount">
            <span class="text-danger" asp-validation-for="Discount"></span>
        </div>
        <div class="form-group">
            <label asp-for="Cookie">Cookie:</label>
            <input class="form-control" style="width:300px" asp-for="Cookie">
            <span class="text-danger" asp-validation-for="Cookie"></span>
        </div>
        <div class="form-group">
            <label asp-for="WeekCount">WeekCount:</label>
            <input class="form-control" style="width:300px" asp-for="WeekCount">
            <span class="text-danger" asp-validation-for="WeekCount"></span>
        </div>
        <button type="submit" class="btn btn-primary me-2">Submit</button>
        <a asp-action="Index" class="btn btn-light">Cancel</a>
    </form>
</div>

FrontProjectInAsp.Net/Areas/AdminArea/Views/Poster/Detail.cshtml
@model Poster
@{
    ViewData["Title"] = "Detail";
    Layout = "~/Areas/AdminArea/Views/Shared/_AdminLayout.cshtml";
}

<div class="container">
    <div class="row">
        <h4>Poster</h4>
        <div class="col-lg-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <div class="header d-flex justify-content-between my-5">
                        <h1 class="card-title my-3">Posters</h1>
                        <div><a class="btn btn-success btn-sm my-4" asp-controller="Poster" asp-action="Create">Create</a></div>




                    </div>
                    <div class="table-responsive">
                        <table class="table table-bordered">
                            <thead>
                                <tr>
                                    <th> Image </th>
                                    <th> Discount </th>
                                    <th> Cookie </th>
                                    <th> WeekCount </th>

                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td> <img style="width: 250px; height: 150px; border-radius: unset" src="~/assets/image/@Model.Image" alt="Slider" /> </td>
                                    <td>@Model.Discount</td>
                                    <td>@Model.Cookie</td>
                                    <td>@Model.WeekCount</td>
                                </tr>
                                <tr>
                                    <a class="btn btn-primary btn-sm" asp-action="Index">Go Back</a>
                                </tr>
                            </tbody>

                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

FrontProjectInAsp.Net/Areas/AdminArea/Views/Poster/Edit.cshtml
@model Poster
@{
    ViewData["Title"] = "Edit";
    Layout = "~/Areas/AdminArea/Views/Shared/_AdminLayout.cshtml";
}

<div class="container mt-5">
    <div class="img">
        <img src="~/assets/img/@Model.Image" alt="Slider" style="width:350px; height:350px" />
    </div>
    <form class="forms-sample" method="post" asp-action="Edit" enctype="multipart/form-data">
        <div class="form-group">
            <label asp-for="Photo"></label>
            <input class="form-control" style="width:300px" asp-for="Photo">
            <span class="text-danger" asp-validation-for="Photo"></span>
        </div>
        <div class="form-group">
            <label asp-for="Discount">Discount:</label>
            <input class="form-control" style="width:300px" asp-for="Discount">
            <span class="text-danger" asp-validation-for="Discount"></span>
        </div>
        <div class="form-group">
            <label asp-for="Cookie">Cookie:</label>
            <input class="form-control" style="width:300px" asp-for="Cookie">
            <span class="text-danger" asp-validation-for="Cookie"></span>
        </div>
        <div class="form-group">
            <label asp-for="WeekCount">WeekCount:</label>
            <input class="form-control" style="width:300px" asp-for="WeekCount">
            <span class="text-danger" asp-validation-for="WeekCount"></span>
        </div>
        <button type="submit" class="btn btn-primary me-2">Submit</button>
        <a asp-action="Index" class="btn btn-light">Cancel</a>
    </form>
</div>

FrontProjectInAsp.Net/Areas/AdminArea/Views/Poster/Index.cshtml
@model List<Poster>
@{ 

    ViewData["Title"] = "Index";
    Layout = "~/Areas/AdminArea/Views/Shared/_AdminLayout.cshtml";
    int count = 1;

}

<div class="container">
    <div class="row">

        <div class="col-lg-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <div class="header d-flex justify-content-between my-5">
                        <h1 class="card-title my-3">Poster</h1>
                        <div><a class="btn btn-success btn-sm my-4" asp-controller="Poster" asp-action="Create">Create</a></div>




                    </div>
                    <div class="table-responsive">
                        <table class="table table-bordered">
                            <thead>
                                <tr>
                                    <th> No </th>
                                    <th> Image </th>
                                    <th> Discount </th>
                                    <th> Cookie </th>
                                    <th> WeekCount </th>
                                    <th> Setting </th>

                                </tr>
                            </thead>
                            <tbody>

                                @foreach (var poster in Model)
                                {
                                    <tr>
                                        <td> @count </td>
                                        <td>   <img style="width:100px; height:50px; border-radius:unset" src="~/assets/img/@poster.Image" alt="Poster" /></td>
                                        <td> @poster.Discount </td>
                                        <td>@poster.Cookie  </td>
                                        <td> @poster.WeekCount </td>
                                        <td>
                                            <a class="btn btn-primary btn-sm" asp-action="Detail" asp-route-Id="@poster.Id"><i class="mdi mdi-account-card-details"></i></a>
                                            <a class="btn btn-inverse-warning btn-sm" asp-action="Edit" asp-route-Id="@poster.Id"><i class="mdi mdi-grease-pencil"></i></a>
                                            <form style="display:inline;" asp-action="Delete" asp-route-Id="@poster.Id">
                                                <button type="submit" class="btn btn-danger btn-sm"><i class="mdi mdi-delete-forever"></i></button>
                                            </form>
                                        </td>
                                    </tr>
                                    count++;
                                }






                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>







    </div>



</div>